#32 ORCID validation case
nfdi4plants/arc-validate pull request #33
Opened 2023-07-18 21:12 UTC by omaus

This PR

- adds a Regex pattern that every ORCID entry must match to succeed the validation
- fixes #32

2023-07-19 13:08 UTC, kMutagene requested changes
Also, there are no tests for this (in this repo).

these are valid orcids:

https://orcid.org/0000-0001-5109-3700
https://orcid.org/0000-0002-1694-233X

2023-07-19 14:19 UTC, omaus commented on src/ArcValidation/Validate/Critical/ValidateCvBase.fs
> +            let rgxPat = System.Text.RegularExpressions.Regex("^\d{4}-\d{4}-\d{4}-\d{4}$")
Yes, this was also already mentioned in #32: https://github.com/nfdi4plants/arc-validate/issues/32#issuecomment-1641081529

2023-07-20 06:58 UTC, kMutagene requested changes
Please add unit tests for the newly added functions (checksum, checkValid)

2023-07-20 07:21 UTC, kMutagene commented
Also correct me if I am wrong, but i think your checks do not cover the allowed number ranges

2023-07-20 15:16 UTC, kMutagene approved these changes

2023-07-21 07:39 UTC, merged